--- #YAML:1.0
name:                Test-MonitorSites
version:             0.14
abstract:            Monitor availability and function of a list of websites 
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    Config::Simple:                0
    Cwd:                           0
    Data::Dumper:                  0
    File::Util:                    0
    HTML::Tidy:                    0
    HTTP::Request::Common:         0
    Mail::Mailer:                  0
    Test::Builder:                 0
    Test::Builder::Tester:         0
    Test::HTML::Tidy:              0
    Test::More:                    0
    Test::Perl::Critic:            0
    Test::Pod:                     1.14
    Test::Pod::Coverage:           1.04
    Test::WWW::Mechanize:          0
    WWW::Mechanize:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Hugh Esco <hesco@greens.org>
