# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-MonitorSites
version:      0.13
version_from: lib/Test/MonitorSites.pm
installdirs:  site
requires:
    Carp:                          0
    Config::Simple:                0
    Cwd:                           0
    Data::Dumper:                  0
    File::Util:                    0
    HTTP::Request::Common:         0
    Mail::Mailer:                  0
    Test::Builder:                 0
    Test::Builder::Tester:         0
    Test::HTML::Tidy:              0
    Test::More:                    0
    Test::Pod:                     1.14
    Test::Pod::Coverage:           1.04
    Test::WWW::Mechanize:          0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
